[platformio]
src_dir = .
default_envs = uno


[env]
platform = atmelavr
board = uno
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_speed=115200

[env:uno]
build_src_filter = +<*.h> +<./src/Communication.cpp> +<./src/main-${PIOENV}.cpp>

[env:thermal]
build_src_filter = +<*.h> +<./src/Communication.cpp> +<./src/main-${PIOENV}.cpp>