; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = uno

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_speed = 115200

[env:uno]
build_src_filter = +<*.h> +<./src/Communication.cpp> +<./src/main-${PIOENV}.cpp>
lib_deps = 
	br3ttb/PID@^1.2.1
	adafruit/Adafruit BusIO@^1.17.4

[env:thermal]
build_src_filter = +<*.h> +<./src/Communication.cpp> +<./src/daqAD5391.cpp> +<./src/main-${PIOENV}.cpp>
lib_deps = 
	br3ttb/PID@^1.2.1
	adafruit/Adafruit BusIO@^1.17.4
